# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='ac',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='char',
            name='atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='char',
            name='dmg',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='char',
            name='hp',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='char',
            name='sp',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='item',
            name='ac',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='atk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='dmg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='sp',
            field=models.IntegerField(default=0),
        ),
    ]
