# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_auto_20180526_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char',
            name='both_hands_item',
        ),
    ]
