# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='123123123123123', max_length=255),
            preserve_default=False,
        ),
    ]
